/**
 * =============================================================================
 * F-A-30 — PricingService.calculateEstimate golden-master parity
 * =============================================================================
 *
 * Loads 50 canned `PriceEstimateRequest` fixtures with their pre-computed v1
 * outputs (generated by `scripts/generate-pricing-fixtures.ts`).
 *
 * For each fixture:
 *   - Set FF_PRICING_V2=true (forces the refactored orchestrator path).
 *   - Invoke pricingService.calculateEstimate(input).
 *   - Assert byte-identical JSON output vs the v1 fixture.
 *
 * Coverage: happy path, surge windows (peak/night/weekend), min-charge,
 * subtype variants, tonnage edge cases, distance-slab boundaries, and the
 * catalog-miss fallback path.
 *
 * RED state (before refactor): FF_PRICING_V2 has no effect, so v1 == v2 and
 * the test passes trivially. We add a strict "v2 is reachable" guard that
 * fails until the new code path actually exists.
 * =============================================================================
 */

jest.mock('../shared/services/logger.service', () => ({
  logger: { info: jest.fn(), warn: jest.fn(), error: jest.fn(), debug: jest.fn() },
}));

import * as fs from 'fs';
import * as path from 'path';

const FIXTURES_PATH = path.resolve(
  __dirname,
  '__fixtures__',
  'pricing-golden-master-fixtures.json'
);

interface Fixture {
  input: {
    name: string;
    vehicleType: string;
    vehicleSubtype?: string;
    distanceKm: number;
    trucksNeeded: number;
    cargoWeightKg?: number;
    cellId?: string;
    timestampMs: number;
  };
  output: Record<string, unknown>;
}

const fixtures: Fixture[] = JSON.parse(fs.readFileSync(FIXTURES_PATH, 'utf8'));

describe('F-A-30 — PricingService golden-master parity (v2 vs v1)', () => {
  const ORIGINAL_FF = process.env.FF_PRICING_V2;
  let pricingService: typeof import('../modules/pricing/pricing.service')['pricingService'];

  beforeAll(() => {
    process.env.FF_PRICING_V2 = 'true';
    // Re-import after the flag is set so the module reads the env at load.
    jest.isolateModules(() => {
      pricingService = require('../modules/pricing/pricing.service').pricingService;
    });
  });

  afterAll(() => {
    if (ORIGINAL_FF === undefined) {
      delete process.env.FF_PRICING_V2;
    } else {
      process.env.FF_PRICING_V2 = ORIGINAL_FF;
    }
  });

  it('loads exactly 50 canned fixtures', () => {
    expect(fixtures).toHaveLength(50);
  });

  it('exports a v2 indicator (refactored orchestrator is wired)', () => {
    // The v2 implementation MUST expose an internal indicator function so
    // this test can verify the refactor is actually exercised, not that the
    // legacy path was silently used. RED until F-A-30 lands.
    const mod = require('../modules/pricing/pricing.service') as Record<string, unknown>;
    expect(typeof mod.__pricingV2Active).toBe('function');
    expect((mod.__pricingV2Active as () => boolean)()).toBe(true);
  });

  describe.each(fixtures.map((f, i) => ({ idx: i, fixture: f })))(
    'fixture #$idx ($fixture.input.name)',
    ({ fixture }) => {
      it('v2 output matches v1 byte-for-byte', () => {
        const { input, output: expectedV1 } = fixture;
        const actual = pricingService.calculateEstimate({
          vehicleType: input.vehicleType,
          vehicleSubtype: input.vehicleSubtype,
          distanceKm: input.distanceKm,
          trucksNeeded: input.trucksNeeded,
          cargoWeightKg: input.cargoWeightKg,
          cellId: input.cellId,
          timestampMs: input.timestampMs,
        });
        // JSON-canonicalize both sides so key ordering and number reps match.
        const actualJson = JSON.stringify(actual);
        const expectedJson = JSON.stringify(expectedV1);
        expect(actualJson).toBe(expectedJson);
      });
    }
  );
});
